services:
  local-llm:
    image: gbenson/hive-local-llm
    init: true
    restart: unless-stopped
    networks:
      - message-bus
    volumes:
      - local_llm:/data
    environment:
      - DO_NOT_TRACK=1
      - HF_HUB_CACHE=/data
      - HF_HUB_OFFLINE=1
      - HF_HUB_VERBOSITY=debug
    secrets:
      - rabbitmq.env
    command:
      - --model
      - HuggingFaceTB/SmolLM2-360M-Instruct

volumes:
  local_llm:
