services:
  gotify:
    image: ${GOTIFY_CONTAINER_IMAGE:-gotify/server}
    restart: unless-stopped
    networks:
      - gotify
    volumes:
      - gotify:/app/data
    environment:
      # GOTIFY_DEFAULTUSER_USER and GOTIFY_DEFAULTUSER_PASS are only
      # used when started with an empty database.  You should set at
      # least GOTIFY_DEFAULTUSER_PASS for your first startup, either
      # in "$HOME/.config/hive/gotify.env" or here, then immediately
      # change the password in the UI once the database is set up.
      - GOTIFY_DEFAULTUSER_USER  # default is "admin"
      - GOTIFY_DEFAULTUSER_PASS=$(GOTIFY_DEFAULTUSER_PASS:-N0tMyPa5sW0rD}

networks:
  gotify:

volumes:
  gotify:
