services:
  email-receiver:
    image: gbenson/hive-service-py
    init: true
    restart: unless-stopped
    networks:
      - email-receiver
      - email-receiver-valkey
      - message-bus
    volumes:
      - ./hive/email_receiver:/venv/lib/python3.11/site-packages/hive/email_receiver:ro
    secrets:
      - rabbitmq.env
      - email.yml
    command:
      - /venv/bin/python3
      - -m
      - hive.email_receiver
    profiles:
      - email-receiver

  email-receiver-valkey:
    image: valkey/valkey:8
    restart: unless-stopped
    networks:
      email-receiver-valkey:
         aliases:
           - valkey
    volumes:
      - email_receiver_valkey:/data
    command:
      - valkey-server
      - --save 60 1
      - --loglevel warning
    profiles:
      - email-receiver

networks:
  email-receiver:
  email-receiver-valkey:
    internal: true

volumes:
  email_receiver_valkey:
