services:
  service-monitor:
    image: gbenson/hive-service-monitor
    restart: unless-stopped
    networks:
      - message-bus
    volumes:
      - service_monitor:/var/lib/hive
    secrets:
      - rabbitmq.env

volumes:
  service_monitor:
