services:
  log-collector:
    image: gbenson/hive-log-collector
    restart: unless-stopped
    networks:
      - "${RABBITMQ_NETWORK:-log-collector-msgbus}"
    extra_hosts:
      - "${RABBITMQ_HOST_IP:-message-bus=127.0.1.1}"
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - /var/log/journal:/var/log/journal:ro
      - log_collector:/var/lib/hive/log-collector
    environment:
      - XDG_STATE_HOME=/var/lib
    secrets:
      - rabbitmq.env

  log-ingester:
    image: gbenson/hive-log-ingester
    restart: unless-stopped
    networks:
      - log-vault
      - "${RABBITMQ_NETWORK:-log-ingester-msgbus}"
    extra_hosts:
      - "${RABBITMQ_HOST_IP:-message-bus=127.0.1.1}"
    secrets:
      - log-ingester.env
      - rabbitmq.env
    profiles:
      - log-vault

  log-vault:
    image: mongo
    restart: unless-stopped
    networks:
      - log-vault
    volumes:
      - ./vault/docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - ./vault/initdb.d:/docker-entrypoint-initdb.d:ro
      - hive_log_vault:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    secrets:
      - log-ingester.env
    entrypoint: /docker-entrypoint.sh
    command:
      - mongod
      - --auth
    profiles:
      - log-vault

networks:
  log-collector-msgbus:
  log-ingester-msgbus:
  log-vault:
    internal: true

volumes:
  log_collector:
  hive_log_vault:
    external: true
