services:
  llm-chatbot:
    image: gbenson/hive-service-py
    init: true
    restart: unless-stopped
    networks:
      - "${RABBITMQ_NETWORK:-llm-chatbot-msgbus}"
    extra_hosts:
      - "${RABBITMQ_HOST_IP:-message-bus=127.0.1.1}"
    volumes:
      - ./hive/llm_chatbot:/usr/lib/hive/llm_chatbot:ro
    secrets:
      - rabbitmq.env
    command:
      - /venv/bin/python3
      - -m
      - hive.llm_chatbot
    profiles:
      - llm-chatbot

networks:
  llm-chatbot-msgbus:
