services:
  nginx-proxy:
    image: nginx
    restart: unless-stopped
    networks:
      - nginx-proxy
    ports:
      - ${INBOUND_HTTPS_PORT:-443}:443/tcp
    volumes:
      - certbot_certs:/etc/letsencrypt:ro
      - ./templates:/etc/nginx/templates:ro
      - ./default_server:/usr/share/nginx/html:ro
    environment:
      - DEFAULT_HOSTNAME

networks:
  nginx-proxy:
