services:
  nginx-proxy:
    image: nginx
    restart: unless-stopped
    networks:
      - nginx-proxy
    ports:
      - 443:443/tcp
    volumes:
      - certbot_certs:/etc/letsencrypt:ro
      - ./templates:/etc/nginx/templates:ro
      - ./default_server:/usr/share/nginx/html:ro
    env_file: $HOME/.config/hive/nginx-proxy.env

networks:
  nginx-proxy:
