services:
  rabbitmq:
    image: rabbitmq:4-management
    restart: unless-stopped
    hostname: $RABBITMQ_HOST
    networks:
      rabbitmq:     # for external connections
      message-bus:  # no external connectivity
        aliases:
          - rabbit  # XXX REMOVE (for non-TLS connections)
    ports:
      - 5671:5671/tcp    # queues
      - 5672:5672/tcp    # queues XXX REMOVE (non-TLS)
      - 15671:15671/tcp  # management
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/conf.d/20-hive.conf.template:ro
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - rabbitmq:/var/lib/rabbitmq
      - hive_certdist_host:/etc/letsencrypt:ro
    secrets:
      - rabbitmq.env
    entrypoint: /docker-entrypoint.sh
    profiles:
      - rabbitmq

networks:
  rabbitmq:
  message-bus:
    internal: true

volumes:
  rabbitmq:
