. /run/secrets/log-ingester.env

test "x$LOG_INGESTER_MONGODB_DATABASE" = "x$MONGO_INITDB_DATABASE" || exit 1

export MONGO_INITDB_USERNAME="$LOG_INGESTER_MONGODB_USERNAME"
export MONGO_INITDB_PASSWORD="$LOG_INGESTER_MONGODB_PASSWORD"

unset LOG_INGESTER_MONGODB_HOST
unset LOG_INGESTER_MONGODB_USERNAME
unset LOG_INGESTER_MONGODB_PASSWORD
unset LOG_INGESTER_MONGODB_DATABASE

env | grep LOG_INGESTER_ && exit 1 || true # crowbar
