services:
  mediawiki-fpm:
    image: gbenson/mediawiki-fpm
    restart: unless-stopped
    networks:
      - mediawiki-fpm
      - mediawiki-mariadb
    profiles:
      - bono

  mediawiki-mariadb-common:
    image: mariadb
    restart: unless-stopped
    networks:
      - mediawiki-mariadb
    volumes:
      - hive_mediawiki_mariadb:/var/lib/mysql
    profiles:
      - disabled

  mediawiki-mariadb:
    extends:
      service: mediawiki-mariadb-common
    profiles:
      - bono

  mediawiki-mariadb-setup:
    extends:
      service: mediawiki-mariadb-common
    restart: no
    env_file: ./initdb.d/00-root-password.env
    volumes:
      - hive_mediawiki_mariadb:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    profiles:
      - mediawiki-mariadb-setup

networks:
  mediawiki-fpm:
    internal: true
  mediawiki-mariadb:
    internal: true

volumes:
  hive_mediawiki_mariadb:
    external: true
