services:
  mediawiki-fpm:
    image: gbenson/mediawiki-fpm
    restart: unless-stopped
    networks:
      - mediawiki-fpm
      - mediawiki-mariadb
    volumes:
      - ./LocalSettings.php:/etc/mediawiki/LocalSettings.php.template:ro
      - ./docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - hive_mediawiki_static:/usr/share/nginx/mediawiki-static
      - hive_mediawiki_uploads:/var/www/html/images
    secrets:
      - hostnames.env
      - mediawiki-mariadb.env
      - mediawiki-paths.env
      - mediawiki-settings.env
    entrypoint: /docker-entrypoint.sh
    command: php-fpm
    profiles:
      - mediawiki

  mediawiki-mariadb:
    image: mariadb
    restart: unless-stopped
    networks:
      - mediawiki-mariadb
    volumes:
      - hive_mediawiki_mariadb:/var/lib/mysql
    profiles:
      - mediawiki

  mediawiki-mariadb-backup:
    image: mariadb
    restart: unless-stopped
    networks:
      - mediawiki-mariadb
    volumes:
      # Piggyback /var/lib/mysql to avoid an anonymous volume.
      - hive_mediawiki_backups:/var/lib/mysql
      - ./backup/docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - ./backup/mariadb-backup.sh:/mariadb-backup.sh:ro
    secrets:
      - mediawiki-mariadb.env
    entrypoint: /docker-entrypoint.sh
    profiles:
      - mediawiki

  mediawiki-uploads-backup:
    image: gbenson/hive-borg-backup
    restart: unless-stopped
    networks:
      - mediawiki-uploads-backup
    volumes:
      - hive_mediawiki_uploads:/srv/mediawiki/uploads:ro
    environment:
      - HIVE_BORG_REPO=/mediawiki/uploads
      - HIVE_DAILY_BACKUP_TIME=4:05am
    secrets:
      - source: backup-server.env
      - source: mediawiki-uploads-backup-client-id_ed25519
        target: id_ed25519
      - source: mediawiki-uploads-backup-passphrase
        target: backup-passphrase
    command: >-
      borg create
      --verbose
      --filter AME
      --list
      --stats
      --show-rc
      --compression auto,zstd,22
      --exclude lost+found
      --exclude lockdir
      --exclude temp
      ::'{now}'
      .
    profiles:
      - mediawiki

networks:
  mediawiki-fpm:
    internal: true
  mediawiki-mariadb:
    internal: true
  mediawiki-uploads-backup:

volumes:
  hive_mediawiki_mariadb:
    external: true
  hive_mediawiki_static:
    external: true
  hive_mediawiki_uploads:
    external: true
  hive_mediawiki_backups:
    external: true
