services:
  mediawiki-fpm:
    image: gbenson/mediawiki-fpm
    restart: unless-stopped
    networks:
      - mediawiki-fpm
      - mediawiki-mariadb
    volumes:
      - ./LocalSettings.php:/etc/mediawiki/LocalSettings.php.template:ro
      - ./docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - hive_mediawiki_static:/usr/share/nginx/mediawiki-static
      - hive_mediawiki_uploads:/var/www/html/images
    secrets:
      - hostnames.env
      - mediawiki-mariadb.env
      - mediawiki-paths.env
      - mediawiki-settings.env
    entrypoint: /docker-entrypoint.sh
    command: php-fpm
    profiles:
      - bono

  mediawiki-mariadb-common:
    image: mariadb
    restart: unless-stopped
    networks:
      - mediawiki-mariadb
    volumes:
      - hive_mediawiki_mariadb:/var/lib/mysql
    profiles:
      - disabled

  mediawiki-mariadb:
    extends:
      service: mediawiki-mariadb-common
    profiles:
      - bono

  mediawiki-mariadb-setup:
    extends:
      service: mediawiki-mariadb-common
    restart: no
    env_file: ./initdb.d/00-root-password.env
    volumes:
      - hive_mediawiki_mariadb:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    profiles:
      - mediawiki-mariadb-setup

  mediawiki-mariadb-backup:
    image: mariadb
    restart: unless-stopped
    networks:
      - mediawiki-mariadb
    volumes:
      # Piggyback /var/lib/mysql to avoid an anonymous volume.
      - hive_mediawiki_backups:/var/lib/mysql
      - ./backup/docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - ./backup/mariadb-backup.sh:/mariadb-backup.sh:ro
    secrets:
      - mediawiki-mariadb.env
    entrypoint: /docker-entrypoint.sh
    profiles:
      - bono

networks:
  mediawiki-fpm:
    internal: true
  mediawiki-mariadb:
    internal: true

volumes:
  hive_mediawiki_mariadb:
    external: true
  hive_mediawiki_static:
    external: true
  hive_mediawiki_uploads:
    external: true
  hive_mediawiki_backups:
    external: true
