<?php
# This file was automatically generated by the MediaWiki 1.24.4
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this for backup/whatever.
#$wgReadOnly = 'Site Maintenance';

## Uncomment this to disable output compression
#$wgDisableOutputCompression = true;

$wgSitename = 'Hive';

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = '/{{ wg_script_path }}';

## The protocol and server name to use in fully-qualified URLs.
$wgServer = 'https://{{ service_hostname }}';

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = '/{{ wg_resource_base_path }}';

## UPO means: this is also a user preference option

$wgEnableEmail = false;
$wgEnableUserEmail = false; # UPO

$wgEmergencyContact = 'webmaster@{{ service_hostname }}';
$wgPasswordSender = 'webmaster@{{ service_hostname }}';

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = false;

## Database settings
$wgDBtype = 'mysql';
$wgDBserver = 'mediawiki-mariadb';
$wgDBname = '{{ mariadb_database }}';
$wgDBuser = '{{ mariadb_user }}';
$wgDBpassword = '{{ mariadb_password }}';

# MySQL specific settings
$wgDBprefix = '';

# MySQL table options to use during installation or update
$wgDBTableOptions = 'ENGINE=InnoDB, DEFAULT CHARSET=binary';

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = '/usr/bin/convert';

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale. This should ideally be set to an English
## language locale so that the behaviour of C library functions will
## be consistent with typical installations. Use $wgLanguageCode to
## localise the wiki.
$wgShellLocale = 'C.UTF-8';

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = 'en';

## A secret, unique string. This value is used as a source of
## cryptographic entropy when no better sources of entropy are
## available. If the value of the variable leaks out you should
## generate a new secret key.
$wgSecretKey = '{{ wg_secret_key }}';

## Site upgrade key. Must be set to a string to turn on the web
## installer while LocalSettings.php is in place.
$wgUpgradeKey = '{{ wg_upgrade_key }}';

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = '/usr/bin/diff3';

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['read'] = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = 'vector';

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'Vector' );

## The relative URL paths of icons and the site logo. The logo size
## should be 135x135 pixels.
$wgLogo = "$wgResourceBasePath/hive/site-logo.png";
$wgFavicon = "$wgResourceBasePath/hive/favicon.ico";
$wgAppleTouchIcon = "$wgResourceBasePath/hive/apple-touch-icon.png";

## https://stackoverflow.com/questions/17824295/
$wgShowExceptionDetails = true;

## https://www.mediawiki.org/wiki/Manual:User_rights
$wgGroupPermissions['reapers']['delete'] = true;

## https://www.mediawiki.org/wiki/Manual:Configuring_file_uploads
$wgFileExtensions[] = 'pdf';
$wgFileExtensions[] = 'svg';
$wgFileExtensions = array_diff( $wgFileExtensions, array ('gif') );
$wgFileExtensions[] = 'zip';
$wgFileExtensions[] = 'txt';

## https://www.mediawiki.org/wiki/Extension:Renameuser
#wfLoadExtension( 'Renameuser' );

## https://www.mediawiki.org/wiki/Extension:Cite
wfLoadExtension( 'Cite' );

## https://www.mediawiki.org/wiki/Extension:Scribunto
wfLoadExtension( 'Scribunto' );
$wgScribuntoDefaultEngine = 'luastandalone';

## https://www.mediawiki.org/wiki/Extension:TemplateStyles
wfLoadExtension( 'TemplateStyles' );

## https://www.mediawiki.org/wiki/Extension:ParserFunctions
wfLoadExtension( 'ParserFunctions' );

## https://www.mediawiki.org/wiki/Extension:Interwiki
wfLoadExtension( 'Interwiki' );
$wgGroupPermissions['sysop']['interwiki'] = true;

## https://www.mediawiki.org/wiki/Manual:Configuring_file_uploads
$wgAllowCopyUploads = true;
$wgCopyUploadsFromSpecialUpload = true;
$wgGroupPermissions['user']['upload_by_url'] = true;

## https://www.semantic-mediawiki.org/wiki/Help:EnableSemantics
#enableSemantics( '{{ service_hostname }}' );

## https://www.semantic-mediawiki.org/wiki/Maps/Installation
#wfLoadExtension( 'Maps' );
#require_once "$IP/extensions/Maps/Maps_Settings.php";

## https://www.mediawiki.org/wiki/Extension:JsonConfig
#wfLoadExtension( 'JsonConfig' );

## https://www.mediawiki.org/wiki/Extension:Graph
#wfLoadExtension( 'Graph' );

## https://www.mediawiki.org/wiki/Extension:SyntaxHighlight#Installation
wfLoadExtension( 'SyntaxHighlight_GeSHi' );

## https://www.mediawiki.org/wiki/Extension:TemplateData
#wfLoadExtension( 'TemplateData' );

## https://www.mediawiki.org/wiki/Manual:Timezone
#$wgLocaltimezone = 'Europe/London';
$wgLocaltimezone = 'UTC';
date_default_timezone_set( $wgLocaltimezone );

## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgArticlePath = '/{{ wg_article_path }}/$1';

## Image uploads.
if ( $wgEnableUploads ) {
   if ( !$wgUploadPath ) {
     $wgUploadPath = '/{{ wg_upload_path }}';
   }
   if ( !$wgUploadDirectory ) {
     $wgUploadDirectory = dirname($IP) . $wgUploadPath;
   }
   if ( $wgSVGConverter == 'ImageMagick' ) {
     $wgSVGConverter = 'rsvg';
   }
}

## https://www.mediawiki.org/wiki/Extension:MobileFrontend
wfLoadExtension( 'MobileFrontend' );
$wgMFDefaultSkinClass = 'SkinMinerva';
