services:
  matrix-router:
    image: gbenson/hive-matrix-router
    init: true
    restart: unless-stopped
    networks:
      - message-bus
    volumes:
      - ./hive/matrix_router:/venv/lib/python3.11/site-packages/hive/matrix_router:ro
    secrets:
      - rabbitmq.env
