services:
  certbot:
    image: certbot/certbot
    restart: no
    networks:
      - certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_webroot:/var/www/letsencrypt
      - certbot_workdir:/var/lib/letsencrypt
    # This default command means it'll print the message and exit with
    # status 0 on "docker compose up", the "restart: no" above stops
    # compose worrying about this, and anyone trying to debug this will
    # presumably run "docker compose logs certbot" and see the message.
    command:
      - certonly
      - --help

  nginx-http:
    image: nginx
    restart: unless-stopped
    networks:
      - nginx-http
    ports:
      - ${INBOUND_HTTP_PORT:-80}:80/tcp
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_webroot:/var/www/letsencrypt:ro

networks:
  default:
  certbot:
  nginx-http:

volumes:
  certbot_webroot:
  certbot_workdir:
