services:
  log-collector:
    image: gliderlabs/logspout
    restart: unless-stopped
    networks:
      - logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - logspout_routes:/mnt/routes
    environment:
      - LOGSPOUT=ignore
      - >-
        RAW_FORMAT={"h":"${COMPOSE_HOSTNAME:-}","c":"{{ .Container.Name
        }}","t":"{{ .Time.Format "2006-01-02T15:04:05.999999999Z07:00"
        }}","s":"{{ .Source }}","m":{{ toJSON .Data }}}
    command:
      - raw://log-forwarder:5000
    profiles:
      - ingress

  log-forwarder:
    image: gbenson/hive-log-forwarder
    restart: unless-stopped
    networks:
      - logspout
      - "${RABBITMQ_NETWORK:-logspout-msgbus}"
    extra_hosts:
      - "${RABBITMQ_HOST_IP:-message-bus=127.0.1.1}"
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    secrets:
      - rabbitmq.env
    environment:
      - LOGSPOUT=ignore
      - LL=debug
    profiles:
      - ingress

networks:
  logspout:
    internal: true
  logspout-msgbus:

volumes:
  logspout_routes:
