services:
  matrix-connector:
    image: gbenson/hive-matrix-connector
    restart: unless-stopped
    networks:
      - matrix-connector
      - "${RABBITMQ_NETWORK:-event-vault}"
    extra_hosts:
      - "${RABBITMQ_HOST_IP:-message-bus=127.0.1.1}"
    volumes:
      - matrix_connector:/var/lib/hive
    environment:
      - XDG_STATE_HOME=/var/lib
    command:
      - hive-matrix-connector
    secrets:
      - rabbitmq.env
      - matrix.yml
    profiles:
      - hivebot

networks:
  matrix-connector:

volumes:
  matrix_connector:
