services:
  matrix-sender:
    image: gbenson/hive-matrix-connector
    init: true
    restart: unless-stopped
    networks:
      - matrix-connector
      - matrix-connector-valkey
      - message-bus
    volumes:
      - matrix_sender:/var/lib/matrix
    command:
      - hive-matrix-sender
    secrets:
      - rabbitmq.env

  matrix-receiver:
    image: gbenson/hive-matrix-connector
    init: true
    restart: unless-stopped
    networks:
      - matrix-connector
      - matrix-connector-valkey
      - message-bus
    volumes:
      - matrix_receiver:/var/lib/matrix
      - matrix_received_media:/var/lib/matrix/media
    command:
      - hive-matrix-receiver
    secrets:
      - rabbitmq.env

  matrix-transitioner:
    image: gbenson/hive-matrix-connector
    init: true
    restart: unless-stopped
    networks:
      - matrix-connector-valkey
      - message-bus
    command:
      - hive-matrix-transitioner
    secrets:
      - rabbitmq.env

  matrix-connector-valkey:
    image: valkey/valkey:8
    restart: unless-stopped
    networks:
      - matrix-connector-valkey
    volumes:
      - matrix_connector_valkey:/data
    command:
      - valkey-server
      - --save
      - 60 1
    hostname: vane-valkey

networks:
  matrix-connector:
  matrix-connector-valkey:
    internal: true

volumes:
  matrix_sender:
  matrix_receiver:
  matrix_received_media:
  matrix_connector_valkey:
