services:
  matrix-sender:
    image: gbenson/hive-matrix-connector
    init: true
    restart: unless-stopped
    networks:
      - matrix-connector
      - matrix-connector-valkey
      - message-bus
    volumes:
      - matrix_sender:/var/lib/matrix
    command:
      - hive-matrix-sender
    secrets:
      - rabbitmq.env

  matrix-receiver:
    image: gbenson/hive-matrix-connector
    init: true
    restart: unless-stopped
    networks:
      - matrix-connector
      - matrix-connector-valkey
      - message-bus
    volumes:
      - matrix_receiver:/var/lib/matrix
      - matrix_received_media:/var/lib/matrix/media
      - $HOME/projects/hive/libs/chat/hive/chat:/venv/lib/python3.11/site-packages/hive/chat:ro
      - $HOME/projects/hive/libs/messaging/hive/messaging:/venv/lib/python3.11/site-packages/hive/messaging:ro
      - $HOME/projects/hive/libs/service/hive/service:/venv/lib/python3.11/site-packages/hive/service:ro
      - $HOME/projects/hive/services/matrix-connector/hive/matrix_connector:/venv/lib/python3.11/site-packages/hive/matrix_connector:ro
    command:
      - hive-matrix-receiver
    secrets:
      - rabbitmq.env

  matrix-connector-valkey:
    image: valkey/valkey:8
    restart: unless-stopped
    networks:
      - matrix-connector-valkey
    volumes:
      - matrix_connector_valkey:/data
    command:
      - valkey-server
      - --save
      - 60 1
    hostname: vane-valkey

networks:
  matrix-connector:
  matrix-connector-valkey:
    internal: true

volumes:
  matrix_sender:
  matrix_receiver:
  matrix_received_media:
  matrix_connector_valkey:
