services:
  ollama-connector:
    image: gbenson/hive-ollama
    init: true
    restart: unless-stopped
    networks:
      - message-bus
      - ollama
    secrets:
      - rabbitmq.env
    profiles:
      - disabled

  ollama:
    image: ollama/ollama
    init: true
    restart: unless-stopped
    networks:
      - ollama
    volumes:
      - hive_ollama_models:/ollama/models
      - ollama_workspace:/root
      - ./models:/root/models
      - $HOME/.ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_MODELS=/ollama/models
    profiles:
      - ollama

networks:
  ollama:

volumes:
  hive_ollama_models:
    external: true
  ollama_workspace:
