services:
  chat-router:
    image: gbenson/hive-chat-router
    init: true
    restart: unless-stopped
    networks:
      - message-bus
    volumes:
      - ./hive/chat_router:/venv/lib/python3.11/site-packages/hive/chat_router:ro
    command:
      - hive-chat-router
    secrets:
      - rabbitmq.env
