services:
  chat-router:
    image: gbenson/hive-service-py
    init: true
    restart: unless-stopped
    networks:
      - message-bus
    volumes:
      - ./hive/chat_router:/usr/lib/hive/chat_router:ro
    secrets:
      - rabbitmq.env
    command:
      - /venv/bin/python3
      - -m
      - hive.chat_router
    profiles:
      - mono
