services:
  event-vault-base:
    image: gbenson/hive-event-vault
    init: true
    restart: unless-stopped
    networks:
      - "${RABBITMQ_NETWORK:-event-vault}"
    extra_hosts:
      - "${RABBITMQ_HOST_IP:-message-bus=127.0.1.1}"
    secrets:
      - rabbitmq.env
    profiles:
      - abstract

  event-vault:
    extends:
      service: event-vault-base
    volumes:
      - hive_event_vault:/data
    command:
      - inbox.emails
      - readinglist.shares
    profiles:
      - event-vault

  debug-event-vault:
    extends:
      service: event-vault-base
    volumes:
      - event_vault:/data
    command:
      - chat.router.rewrites
      - matrix.events
      - ollama.api.requests
      - ollama.api.responses
    profiles:
      - debug-event-vault

networks:
  event-vault:

volumes:
  event_vault:
  hive_event_vault:
    external: true
