services:
  event-vault:
    image: gbenson/hive-event-vault
    init: true
    restart: unless-stopped
    networks:
      - event-vault
    extra_hosts:
      - "${RABBITMQ_HOST}=${RABBITMQ_IP}"
    volumes:
      - event_vault:/data
    secrets:
      - rabbitmq.env
    command:
      - readinglist.shares
    profiles:
      - event-vault

networks:
  event-vault:

volumes:
  event_vault:
