services:
  event-vault:
    image: gbenson/hive-event-vault
    init: true
    restart: unless-stopped
    networks:
      - "${RABBITMQ_NETWORK:-event-vault}"
    extra_hosts:
      - "${RABBITMQ_HOST_IP:-message-bus=127.0.1.1}"
    volumes:
      - hive_event_vault:/data
    secrets:
      - rabbitmq.env
    command:
      - chat.router.rewrites
      - inbox.emails
      - matrix.events
      - ollama.api.requests
      - ollama.api.responses
      - readinglist.shares
    profiles:
      - event-vault

networks:
  event-vault:

volumes:
  hive_event_vault:
    external: true
