services:
  event-vault:
    image: gbenson/hive-event-vault
    init: true
    restart: unless-stopped
    networks:
      - message-bus
    volumes:
      - event_vault:/data
    secrets:
      - rabbitmq.env
    command:
      - inbox.emails
      - ollama.api.requests
      - ollama.api.responses
      - matrix.events
      - readinglist.shares
      - readinglist.updates
      - service.status
      - service.status.reports

volumes:
  event_vault:
