name: hive-mediawiki

on:
  push:
    tags:
      - "hive-mediawiki-[0-9]+.[0-9]+.[0-9]+-[0-9]+-fpm"

jobs:
  build:
    name: Build and push hive-mediawiki-fpm
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/mediawiki

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Collect Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: gbenson/mediawiki
          tags: |
            type=match,pattern=hive-mediawiki-(\d+\.\d+\.\d+-\d+),group=1
            type=match,pattern=hive-mediawiki-(\d+\.\d+\.\d+),group=1
            type=match,pattern=hive-mediawiki-(\d+\.\d+),group=1
          flavor: |
            suffix=-fpm

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: services/mediawiki
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/hive-mediawiki-') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GITHUB_SERVER_URL=${{ github.server_url }}
            GITHUB_REPOSITORY=${{ github.repository }}
            GITHUB_SHA=${{ github.sha }}
