name: hive-matrix-connector

on:
  push:
    tags:
      - "hive-matrix-connector-[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build and push hive-matrix-connector
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Write __version__.py
        if: startsWith(github.ref, 'refs/tags/hive-matrix-connector-')
        run: ./ci/write-version-py services/matrix-connector/hive/matrix_connector

      - name: Collect Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: gbenson/hive-matrix-connector
          tags: |
            type=match,pattern=hive-matrix-connector-(\d+\.\d+\.\d+),group=1

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          file: services/matrix-connector/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/hive-matrix-connector-') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
