name: make-check-go

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libolm-dev libsystemd-dev
          version: 1.0

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run tests
        run: make check

      - name: Generate coverage report
        run: make coverage.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: make-check
          path: coverage.*
